#!/bin/bash
fullname=$1
pname=${fullname%.*}
if [ -f 'config_plugin.txt' ]; then
	add_plugin=`cat config_plugin.txt | tr '\n' ' '`
else
	add_plugin='cordova-plugin-zeroconf cordova-plugin-ble-central'
fi

echo "Generate SPA from $fullname"
tac-spa "$fullname" &&
cordova create $pname --no-telemetry &&
cp "$pname.html" "$pname/www/index.html" &&
cp -r `npm root -g`/tac-builder/lib "$pname/www/lib" &&
cd "$pname" &&
echo "Generate Android and iOS projects for project name: $pname" &&
cordova platform add android ios --no-telemetry &&
cordova plugin add $add_plugin --no-telemetry &&
cd .. &&
echo "Project folder $pname is genearted with your YAML defined html copied into $pname/www." &&
echo "You can add script in $pname/www/js/index.js to chagne behavior of your app." 
