#!/usr/bin/env node
// simple template engine to generate SPA for Tac
// arron@t2t.io
// (c) 2017

var YAML = require('yamljs')
var HTML = require('html')
var fs = require('fs')
var process = require('process')
var pug = require('pug')
const cheerio = require('cheerio')
const execSync = require('child_process').execSync
const path = require('path')

var jqmHead = `<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>TAC template</title>
 	<link rel="stylesheet" href="lib/jquery.mobile-1.4.5.min.css">
	<script src="lib/jquery.min.js"></script>
 	<script src="lib/jquery.mobile-1.4.5.min.js"></script>
 	<script src="lib/handlebars.min.js"></script>
</head>`

var jsTail = `<script type="text/javascript" src="cordova.js"></script>
<script type="text/javascript" src="js/index.js"></script>
</body>`

try{
	jqmHead = fs.readFileSync('config_head_template.txt').toString()
}catch(e){
	console.log('No config_head_template.txt, use default setting.')
}

try{
	jsTail = fs.readFileSync('config_foot_js.txt').toString()
}catch(e){
	console.log('No config_foot_js.txt, use defeault setting.')
}

// var pageTemplate = fs.readFileSync('page_template').toString()

// check if the input is xlsx or yaml
var filearg = process.argv[2]
var ext = path.extname(filearg)
var yamlName
if(ext === '.xlsx' || ext === 'xls'){
	yamlName = path.basename(filearg, ext) + '.yaml'
	execSync('xlsx2yaml '+filearg+' > '+yamlName)
}else if(ext ==='.yaml'){
	yamlName = filearg
}else{
	console.log('Please add file extension name to .xlsx, .xls or .yaml to help programe detect your input type.')
	process.exit();
}
var htmlName = path.basename(filearg, ext) + '.html'

var yamlContent = fs.readFileSync(yamlName).toString()

var pages = YAML.parse(yamlContent)
// console.log('start to process::\n', pages)

// var finalOutput = '';
var $ = cheerio.load("<div id = 'tacHtmlTop'>")

for (var i=0;i<pages.length;i++){
	thePage = pages[i]
	// console.log('processing:\n',thePage)

	if(thePage.hasOwnProperty('id')){
		$("#tacHtmlTop").append($("<div data-role='page' id='"+thePage.id+"'>"))
	}else{
		console.log('Error: page id missing for \n', thePage)
		process.exit()
	}
	if(thePage['header']){
		$("#"+thePage.id).append("<div data-role='header'><h1>"+thePage.header)
	}
	if(thePage['content']){
		$("#"+thePage.id).append("<div role='main' class='ui-content'>")
		for(var j =0;j<thePage.content.length;j++){
			var item = thePage.content[j]
			switch(item['type']){
				case 'button':
					$("#"+thePage.id + " .ui-content").append($("<p><a href='#"+item['link']+"' class='ui-btn ui-shadow ui-corner-all'>" + item['text']))
				break;
				case 'raw':
					$("#"+thePage.id + " .ui-content").append(item['text'])
				break;
				case 'pug':
					$("#"+thePage.id + " .ui-content").append(pug.render(item['text']))
				break;
			}
		}
	}
	if(thePage['footer']){
		$("#"+thePage.id).append("<div data-role='footer'><h4>"+thePage.footer)
	}
}

var beautify = require('html')
var resultStr = beautify.prettyPrint($.html().replace("<head></head>", jqmHead).replace("<html>", "<!DOCTYPE html><html>").replace("</body>", jsTail))
fs.writeFileSync(htmlName,resultStr)